version: 2

sources:
  - name: raw
    database: NETFLIX_DB
    schema: RAW

    tables:
      - name: titles
      - name: credits

models:

  - name: stg_titles

    columns:

      - name: id
        tests:
          - unique
          - not_null

      - name: title
        tests:
          - not_null

      - name: type
        tests:
          - not_null

  - name: stg_credits

    columns:

      - name: person_id
        tests:
          - not_null

      - name: id
        tests:
          - not_null